services:
  db:
    image: postgres:16
    container_name: gp1-postgres
    restart: always
    environment:
      POSTGRES_USER: gp1
      POSTGRES_PASSWORD: gp1pass
      POSTGRES_DB: gp1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
